database:
  echo: false
  url: sqlite:///detection_system.db
detection:
  confidence_threshold: 0.6
  model_path: models/yolo_v8.pt
  nms_threshold: 0.4
logging:
  file_path: logs/aidcis.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: DEBUG
paths:
  assets_dir: assets
  data_dir: Data
  temp_dir: temp_charts
performance:
  cache_size: 2000
  max_workers: 8
ui:
  font_size: 14
  theme: light
  window_size:
  - 1400
  - 900
